const images = {
  //splashscreen
  // home_select:require("../assets/home.png"),
  // test_select:require("../assets/test.png"),
  // save_select:require("../assets/save.png"),
  // learn_select:require("../assets/learn.png"),
  // connect_select:require("../assets/connect.png"),

  // home_grey:require("../assets/home_grey.png"),
  // test_grey:require("../assets/test_grey.png"),
  // save_grey:require("../assets/save_grey.png"),
  // learn_grey:require("../assets/learn_grey.png"),
  // connect_grey:require("../assets/connect_grey.png"),
  
  // green_tick:require("../assets/check.png"),
  // discard:require("../assets/discard.png"),
  // logo:require("../assets/logo.png"),
  // deliveries_select:require("../assets/deliveries_select.png"),
  // deliveries_unselect:require("../assets/deliveries_unselect.png"),
  // order_select:require("../assets/order_select.png"),
  // order_unselect:require("../assets/order_unselect.png"),
  // profile_select:require("../assets/profile_select.png"),
  // profile_unselect:require("../assets/profile_unselect.png"),
  // food:require("../assets/food.png"),
  // restaurant:require("../assets/restaurant.png"),
  // bag:require("../assets/bag.png"),
  // plate:require("../assets/plate.png"),
  // location:require("../assets/location.png"),
  // call:require("../assets/call.png"),
  // search:require("../assets/search.png"),
  // cancel:require("../assets/cancel.png"),
  // feed:require("../assets/feed.png"),
  // diary:require("../assets/diary.png"),
  // upload:require("../assets/upload.png"),
  home:require("../Assets/home.png"),
  request:require("../Assets/request.png"),
  hotel:require("../Assets/hotel.png"),
  logo:require("../Assets/logo.png"),
  profileimage:require("../Assets/hotel_one.jpg"),
  // spinner:require("../Assets/spinner.gif"),
};

export default images;